### ISSUE TITLE
Installation issues on R < 4.1

### ISSUE THREAD

**Issue by ebein** [kkholst/lava#12]
The latest package version uses the `\(x)` anonymous function notation in the `pairwise.diff` function. This syntax is not supported in R versions prior to 4.1, causing package installation to fail. 

```/tmp/RtmpmitJXO/R.INSTALL5fd596f2af0/lava/R/contr.R:47:53: unexpected input
46: pairwise.diff <- function(n) {
47:   pdiff <- function(n) lava::contr(lapply(seq(n-1), \
                                                        ^
ERROR: unable to collate and parse R files for package lava```

**Comment by kkholst** [comment]
Thanks, this is fixed on the main+develop branch. I will submit a new version to CRAN.
