### ISSUE TITLE
trend.delta in 'spaghetti' function doesn't change shading region when altered

### ISSUE THREAD

**Issue by lukewbonham** [kkholst/lava#2]
Hi Klaus,

Hope you are doing well. I am trying to change the confidence region interval for a spaghetti plot I am making using the trend.delta specification in the 'spaghetti' function. When I alter the value for trend.delta, the shaded region does not change. This seems to be the case using my data as well as in the generated data in the example provided online:
These two 
if (interactive() & requireNamespace("mets")) {
+     K <- 5
+     y <- "y"%++%seq(K)
+     m <- lvm()
+     regression(m,y=y,x=~u) <- 1
+     regression(m,y=y,x=~s) <- seq(K)-1
+     regression(m,y=y,x=~x) <- "b"
+     d <- sim(m,500)
+     dd <- mets::fast.reshape(d);
+     dd$num <- dd$num+rnorm(nrow(dd),sd=0.5) ## Unbalance
+     spaghetti(y~num,dd,id="id",lty=1,col=Col(1,.4),trend=TRUE,trend.col="darkblue")
+ }

The resulting plot when I specify trend.delta=0.05 and trend.delta=0.5 for dd is the same

Sorry if this is an error on my part -- I am not especially strong in R. Any advice you have on how to fix this would be greatly appreciated. If you need any additional information from me or if I can help to resolve this please let me know.

Thanks

**Comment by kkholst** [comment]
I have added a new argument 'level' (default 0.95) to the function (f08f563) which controls the level of the pointwise confidence limits, i.e., 
spaghetti(..., level=0.99)

**Comment by lukewbonham** [comment]
Looks great. Thanks for your help!
