### ISSUE TITLE
Error when removing the last external parameter

### ISSUE THREAD

**Issue by bozenne** [kkholst/lava#3]
Hi Klaus, 

I get an error when I remove the last external parameter from an lvm model (lava version 1.4.4.13):
lv1 <- lvm(Y ~ X1 + X2)
parameter(lv1) <- "Y~X3"
parameter(lv1) <- "Y~X4"
coef(lv1)
parameter(lv1, remove = TRUE) <- "Y~X3"
coef(lv1)
parameter(lv1, remove = TRUE) <- "Y~X4"
# Error in x$exfix[enamed] : invalid subscript type 'list'

I tried to look at what was going on, the error appears
in "parameter<-.lvm" line "index(x) <- reindex(x)"
Then in the reindex function the line:
"eparname <- unlist(unique(x$exfix[enamed]))" 
is problematic as enamed is an empty list.
A possible solution (for my small example) is to replace this line by:

if(length(enamed)>0){
    eparname <- unlist(unique(x$exfix[enamed]))
  }else{
    eparname <- NULL
  }

Thanks!

**Comment by kkholst** [comment]
Thanks for the fix! Now in 082f97f.
