### ISSUE TITLE
Rate vs. scale in coxExponential.lvm

### ISSUE THREAD

**Issue by bozenne** [kkholst/lava#7]
Hi Klaus,

Someone made me notice that the argument rate in coxExponential.lvm should actually be called scale
to be consistent with the rexp function in R.
A small example:

`
p.rate <- 5;
m <- lvm(Y~1);
distribution(m,"Y") <- coxExponential.lvm(rate = p.rate)
set.seed(10);
round(quantile(lava::sim(m, 1e4)[,1]),3)
`
gives something much closer to 
`
set.seed(10);
round(quantile(rexp(1e4, rate = 1/p.rate)),3)
`
than
`
set.seed(10);
round(quantile(rexp(1e4, rate = p.rate)),3)
`

**Comment by kkholst** [comment]
Finally fixed :)
