### ISSUE TITLE
Ordinal regression

### ISSUE THREAD

**Issue by xiaomeng-wang** [kkholst/lava#9]
Hi Klaus,

I wanted to add a multinomial variable to the model:
`m <- lvm()`
`distribution(m, ~y) <- multinomial.lvm(m, prob=c(0.2, 0.2, 0.6)`
But I got the error <could not find function "multinomial.lvm"> (which is however listed in the reference manual)

Thanks!

**Comment by kkholst** [comment]
You can use the 'categorical' method instead
```
m <- lvm()
m <- categorical(m, p=c(.2, .3, .5), ~y)
```
or specify a custom distribution in the following way:
```
m <- lvm()
distribution(m, ~y) <- function(n, ...) sample(seq_along(prob), n, prob=prob, replace=TRUE)
```
In this way you can also easily define a 'multinomial' function:
```
multinomial.lvm <- function(prob)
    structure(function(n, ...) sample(seq_along(prob), n, prob=prob, replace=TRUE),
              family=list(family='multinomial', par=prob))

m <- lvm()
distribution(m, ~y) <- multinomial.lvm(prob=c(.2, .3, .5))
```

**Comment by kkholst** [comment]
For regression models you can also consider the 'ordinal' method which specifies a cumulative Probit model:
```
p <- c(.2, .3, .5)
br <- qnorm(cumsum(p)[-3])

m <- lvm(y ~ x)
ordinal(m, breaks=br) <- ~y
```
```
d <- sim(m, 1e4, seed=1)
a <- ordreg(y ~ x, data=d)
a
```
> Call:
> ordreg(formula = y ~ x, data = d)
>
> Parameter Estimates:
>       0|1        1|2          x 
> -0.8354508 -0.1896797  1.0054458 

Note, to get the intercept parameters back to the original scale in the above model fit, you can use the following

```
lava:::ordreg_threshold(coef(a)[1:2])
```
>          0|1          1|2 
> -0.835209040  0.001052857

**Comment by xiaomeng-wang** [comment]
Many thanks! This is very helpful!

**Comment by xiaomeng-wang** [comment]
Hi Klaus,

May I continue to ask if it's possible to proceed inversely to **build a multivariate ordinal probit(or logistic) regression model with the estimated parameters** so that I can do some simulations?

For example:

- outcome variable: y (ordinal: 1, 2, 3 with prob=c(.2, .3, .5))
- predictor variables: x1, x2 (both follow normal distribution)

> # add ordinal outcome variable
p <- c(.2, .3, .5)
br <- qnorm(cumsum(p)[-3])
m <- lvm()
ordinal(m, breaks=br) <- ~y
# add predictor variables
distribution(m, ~ x1 + x2) <- list(normal.lvm(mean=10, sd=2), normal.lvm(mean=20, sd=2))
# add regression
regression(m) <- y ~ 1.01*x1 + 0.9*x2

But this way the proportions of values in the outcome variable will change dramatically.

**Comment by klaus-holst** [comment]
I don't see an easy way of doing this. The parameters you set in the model are specifying the _conditional distribution_ of y given x1 and x2. You could probably tweak the mean and variance of x1 and x2 (or the regression coefficients) such that after integrating out these variables, you get the desired _marginal probabilities_ of y. I guess you could set up some numerical integration and try to automatically optimize these parameters, but it is not available as a functionality in `lava`.
